### ISSUE TITLE
Contacts.Plugin.Android:  "the bind value at index 20 is null"

### ISSUE THREAD

**Issue by DavidYKay** [jamesmontemagno/Xamarin.Plugins#39]
I haven't stepped through the ContactsPlugin code just yet to figure out what element "index 20" corresponds to, but it looks like we're not handling a null value coming back from the contacts DB properly.

Will update if I find any more info.

Thanks! 

[Exception stacktrace](https://gist.github.com/DavidYKay/30664b723250d8288dac)

**Comment by dhaligas** [comment]
I am also seeing this issue as well.  Causing my app to crash.

**Comment by getmoble** [comment]
Any progress on this one, I am also facing the same issue.

**Comment by jamesmontemagno** [comment]
This one is a bit tricky as I haven't been able to reproduce on my devices. Are you able to test with the source code? Also you could try Xamarin.Mobile and see if you get the crash there as well.

I am not seeing a lot via the log.

**Comment by jamesmontemagno** [comment]
Actually, can you please try alpha 3, which I just pushed.

**Comment by NamXH** [comment]
The problem still persists on alpha 3. I got it when iterating through CrossContacts.Current.Contacts. Calling CrossContacts.Current.Contacts.ToList() also causes the app to crash too.

Fyi, the "index 20" is not the 20th element in CrossContacts.Current.Contacts.

**Comment by jamesmontemagno** [comment]
Can you please try alpha 4, I think this is all fixed up now.

Additionally, it is an IQueryable that is returned and you can not do a .ToList() on it anymore you would need to copy it locally (this will take time though). 

Here is my recommendation:

```
this.IsBusy = true;
                IOrderedQueryable<Contact> contacts = null;
                CrossContacts.Current.PreferContactAggregation = false;
                long ms1 = 0;
                long ms2 = 0;
                var contactList = new List<Contact>();
                await Task.Run(() =>
                    {
                        var watch = Stopwatch.StartNew();
                        if (CrossContacts.Current.Contacts == null)
                            return;

                        contacts = CrossContacts.Current.Contacts
                            .Where(c => !string.IsNullOrWhiteSpace(c.LastName) && (c.Emails.Count > 0 || c.Phones.Count > 0))
                            .OrderBy(c => c.LastName);

                        watch.Stop();
                        ms1 = watch.ElapsedMilliseconds;
                        //This is very fast (around 35 MS)

                        watch = Stopwatch.StartNew();
                        foreach (var contact in contacts)
                            contactList.Add(contact);
                        watch.Stop();
                        ms2 = watch.ElapsedMilliseconds;
                        //Slower, around 6s for 1400 items
                        //you can actually bind to just contacts for Xamarin.Forms though.
                    });
                

                contactsList.ItemsSource = contactList;

                this.Title = "Contacts: " + contactList.Count + " in " + ms1 + " MS" + " & " + ms2 + " Ms";
                
```

**Comment by rafelcnet** [comment]
Hello, I did your recommendation: update to Alpha 4 and use your code above, but problem still persists, in may case "Java.Lang.IllegalArgumentException: the bind value at index 16 is null".

**Comment by jamesmontemagno** [comment]
Can you give me more context onto the devices you are testing it on? Additionally if you could debug the source code that would be great as I have never seen this.

**Comment by rafelcnet** [comment]
yes, let me debug the source code and try to find what is happened

I'm using a Galaxy 6 Edge

**Comment by EduardoSerra** [comment]
This is happening to me since I deleted a contact in the Android emulator. I'm using the latest version and haven't been able to solve it yet.

**Comment by softsan** [comment]
Downloaded 2.0.2-beta1. it worked fine on my MotoG3- android Marshmallow. But it failed on Android LG G3 on Marshmallow with the error:

`Java.Lang.IllegalArgumentException: the bind value at index 66 is null`

Any thoughts on this?
