### ISSUE TITLE
IsRemoteReachable always False when URL format is invalid

### ISSUE THREAD

**Issue by Yenthe666** [jamesmontemagno/Xamarin.Plugins#46]
Hi James,

First of all, thank you for sharing this, its great.
I've noticed an annoying feature that should be easily fixed though.
When you do this:
<code>
Boolean reachable = await CrossConnectivity.Current.IsRemoteReachable("http://www.google.com", 80, 5000) ? true : false;
                Debug.WriteLine("Reachable: " + reachable);
</code>
It will <b>always</b> return False, even when there is internet connection and it is reachable.
When you do this:
<code>
Boolean reachable = await CrossConnectivity.Current.IsRemoteReachable("google.com", 80, 5000) ? true : false;
                Debug.WriteLine("Reachable: " + reachable);
</code>
It will work and return True or False depending on your connection.
Could you add the option that http://www.???.com and http://??.com are also supported in the call? You could simply find and remove the first part (http:// or http://www) and would make the API much easier to use, especially for beginners. This isn't documented anywhere and left me searching for an hour just to remove http://www.

**Comment by jamesmontemagno** [comment]
I will have to remove the http:// or http://www. in this case, I am not sure why that is the case, but will update it soon. Thanks.

**Comment by Yenthe666** [comment]
I've tested it on Android, it doesn't work there.

**Comment by jamesmontemagno** [comment]
Fixed in 1.0.2

**Comment by SagarPanwala** [comment]
I'm still facing the problem in version 2.2.12. However it is working fine in Android, but always shows IsRemoteReachable = false. So please fix this.

**Comment by Nikygm** [comment]
Hi James, 
I'm also experiencing this issue in 2.2.12.
 `statement = await CrossConnectivity.Current.IsReachable(myCorrectURL, timeout);` is always returning false even though I can access the URL. This part is working fine in iOS though !

**Comment by jamesmontemagno** [comment]
You can post an issue at: https://github.com/jamesmontemagno/ConnectivityPlugin also, you will need to give me the URL you are using so I can test it.
